name: Check

on: push

jobs:
  Execute:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - name: Check the commit message(s)
        uses: mristin/opinionated-commit-message@v1.0.6

      - name: Install .NET core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'

      - name: Install dotnet tools
        working-directory: src
        run: dotnet tool restore

      - name: Check formating
        working-directory: src
        run: dotnet format --check

      - name: Build
        working-directory: src
        run: powershell .\Release.ps1
